/*
 * Editing the sequence after the agent has built it.
 *
 * The tree is not a gallery of independent images. Each step EDITS the frame
 * before it, so the chain from the avatar to the last frame is a single
 * continuous take — which is what makes the sequence read as a storyboard
 * rather than six unrelated pictures.
 *
 * That is also what makes editing it non-trivial. Swapping frame 3 for an
 * alternate does not just change frame 3: frames 4, 5 and 6 were generated by
 * editing the OLD frame 3, so they now descend from an image that is no longer
 * in the sequence. They are not wrong, exactly — they are answers to a question
 * that was withdrawn.
 *
 * So the operations here do two things: rewire the lineage, and mark what the
 * rewiring invalidated. Nothing is regenerated automatically. Every rebuilt step
 * is a paid generation and twenty seconds of somebody's time, so the decision
 * to spend that belongs to the person, with the count and the cost in front of
 * them.
 *
 * Nothing is deleted either. A replaced frame stays on the canvas as an
 * alternate, because the tree's whole claim is that it shows what happened.
 */
import { FieldValue } from 'firebase-admin/firestore';
import { adminDb } from './firebaseAdmin';

import {
  descendantsOf,
  lineageOf,
  summarise,
  type LineageNode,
  type RewireResult,
} from './sequence';

/* Re-exported so existing importers keep working and there is still one
   definition of each. */
export {
  lineageOf,
  descendantsOf,
  isOutOfSequence,
  shotPlan,
  rebuildEstimate,
  type LineageNode,
  type RewireResult,
} from './sequence';

async function loadNodes(runId: string): Promise<LineageNode[]> {
  const snap = await adminDb().collection('runs').doc(runId).collection('nodes').orderBy('createdAt').get();
  return snap.docs.map((d) => ({ id: d.id, ...(d.data() as Omit<LineageNode, 'id'>) }));
}

/**
 * Put `replacementId` where `targetId` sits in the sequence.
 *
 * Both are attempts at the same step with the same parent, so the swap is a
 * re-pointing of children rather than a move: whatever was built on top of the
 * target is now built on top of the replacement. The target stays on the canvas
 * as an alternate.
 */
export async function promoteFrame(runId: string, targetId: string, replacementId: string): Promise<RewireResult> {
  const db = adminDb();
  const nodesRef = db.collection('runs').doc(runId).collection('nodes');
  const nodes = await loadNodes(runId);

  const target = nodes.find((n) => n.id === targetId);
  const replacement = nodes.find((n) => n.id === replacementId);
  if (!target || !replacement) throw new Error('no such frame');
  if (replacement.kind !== 'frame' || target.kind !== 'frame') throw new Error('only frames can be swapped');
  if (!replacement.frameUrl) throw new Error('that frame has no image yet');

  const children = nodes.filter((n) => n.parentId === targetId);

  const batch = db.batch();
  for (const child of children) {
    batch.update(nodesRef.doc(child.id), { parentId: replacementId, stale: true });
  }
  // The replacement takes the target's place in the numbering, so the plan and
  // the canvas agree about which step this is.
  batch.update(nodesRef.doc(replacementId), { stepNo: target.stepNo, stale: false });
  await batch.commit();

  // Everything downstream is stale, not just the direct children: step 5 was
  // edited from step 4, which was edited from the frame that just changed.
  const result = summarise(children.flatMap((c) => [c, ...descendantsOf(nodes, c.id)]));
  if (result.staleIds.length) {
    const b2 = db.batch();
    for (const id of result.staleIds) b2.update(nodesRef.doc(id), { stale: true });
    await b2.commit();
  }
  return result;
}

/**
 * Take a frame out of the sequence.
 *
 * Its children reattach to its parent, so the chain stays unbroken and the
 * steps after it still have something to have been edited from. They are stale
 * for the same reason as a swap: their source changed.
 */
export async function removeFrame(runId: string, nodeId: string): Promise<RewireResult> {
  const db = adminDb();
  const nodesRef = db.collection('runs').doc(runId).collection('nodes');
  const nodes = await loadNodes(runId);

  const node = nodes.find((n) => n.id === nodeId);
  if (!node) throw new Error('no such frame');
  if (node.id === 'root') throw new Error('the source avatar cannot be removed');

  if (node.removedFromSequence) throw new Error('that frame is already out of the sequence');

  /*
   * Only the FRAMES move up.
   *
   * This reattached every child, including rendered clips. A clip belongs to
   * the frame it was made from, not to the sequence, and moving one onto the
   * grandparent made that grandparent read as "already rendered" — its Render
   * button disabled, pointing at a clip generated from a completely different
   * frame. The clip stays with its source, which is also where it is true.
   */
  const children = nodes.filter((n) => n.parentId === nodeId && n.kind === 'frame');
  const newParent = node.parentId ?? 'root';

  const batch = db.batch();
  for (const child of children) batch.update(nodesRef.doc(child.id), { parentId: newParent, stale: true });
  /* Marked rather than deleted: the canvas is a record of what happened, and a
     frame that silently vanishes makes the record a lie.

     Only the one flag. This also wrote status:'rejected', which made the node
     claim two different things about itself — the tree draws "taken out" for
     the flag and "you rejected this" for the status, both absolutely positioned
     at the same offset, so they rendered on top of each other. Taking a frame
     out is not a verdict on it; it is often removed BECAUSE it was fine
     somewhere else. */
  batch.update(nodesRef.doc(nodeId), {
    removedFromSequence: true,
    /* What to hand back if this is undone. Nothing cleared this flag anywhere
       in the codebase, so taking a frame out was a one-way door — and without
       a record of which children were lifted off it, putting it back would be
       guesswork: they now point at its parent, and nothing else says they ever
       pointed here. */
    reattachedOnRemoval: children.map((c) => c.id),
  });
  await batch.commit();

  const result = summarise(children.flatMap((c) => [c, ...descendantsOf(nodes, c.id)]));
  if (result.staleIds.length) {
    const b2 = db.batch();
    for (const id of result.staleIds) b2.update(nodesRef.doc(id), { stale: true });
    await b2.commit();
  }
  return result;
}


/**
 * Put a frame back into the sequence.
 *
 * The counterpart that did not exist. `removedFromSequence` was written in
 * exactly one place and cleared in none, so "Take out of the sequence" was a
 * one-way door: a frame taken out by mistake stayed out for the life of the
 * run, and the only way forward was to pay to regenerate a frame that was
 * sitting right there on the canvas.
 *
 * Undoing a removal means handing back the children the removal lifted off it,
 * which is why removeFrame records them. Those children are stale afterwards
 * for the same reason they were stale when they left: their source changed.
 * The restored frame itself is not — its own parent never moved.
 */
export async function restoreFrame(runId: string, nodeId: string): Promise<RewireResult> {
  const db = adminDb();
  const nodesRef = db.collection('runs').doc(runId).collection('nodes');
  const nodes = await loadNodes(runId);

  const node = nodes.find((n) => n.id === nodeId);
  if (!node) throw new Error('no such frame');
  if (!node.removedFromSequence) throw new Error('that frame is already in the sequence');

  // Only children that still exist, and only ones that have not since been
  // built on somewhere else.
  const returning = (node.reattachedOnRemoval ?? []).filter((id) =>
    nodes.some((n) => n.id === id && n.parentId === (node.parentId ?? 'root')),
  );

  const batch = db.batch();
  batch.update(nodesRef.doc(nodeId), {
    removedFromSequence: FieldValue.delete(),
    reattachedOnRemoval: FieldValue.delete(),
  });
  for (const id of returning) batch.update(nodesRef.doc(id), { parentId: nodeId, stale: true });
  await batch.commit();

  const moved = returning.map((id) => nodes.find((n) => n.id === id)!).filter(Boolean);
  const result = summarise(moved.flatMap((c) => [c, ...descendantsOf(nodes, c.id)]));
  if (result.staleIds.length) {
    const b2 = db.batch();
    for (const id of result.staleIds) b2.update(nodesRef.doc(id), { stale: true });
    await b2.commit();
  }
  return result;
}

/**
 * Disconnect a node — a frame OR a rendered clip.
 *
 * The user-facing half of delete. Detaching and destroying are two different
 * risks, so they are two different actions: disconnecting is instant, reversible
 * and costs nothing, and it is the only way to reach delete. Nothing can be
 * destroyed straight off the canvas by one click on a menu item.
 *
 * Clips are leaves, so there is nothing to reattach; frames hand their children
 * up to their parent exactly as before, so the chain stays unbroken.
 */
export async function disconnectNode(runId: string, nodeId: string): Promise<RewireResult> {
  const nodes = await loadNodes(runId);
  const node = nodes.find((n) => n.id === nodeId);
  if (!node) throw new Error('no such node');
  if (node.kind === 'avatar' || node.id === 'root') throw new Error('the source avatar cannot be disconnected');

  if (node.kind === 'frame') return removeFrame(runId, nodeId);

  if (node.removedFromSequence) throw new Error('that clip is already disconnected');
  await adminDb()
    .collection('runs')
    .doc(runId)
    .collection('nodes')
    .doc(nodeId)
    .update({ removedFromSequence: true, reattachedOnRemoval: [] });
  // A clip has nothing hanging off it, so nothing became stale.
  return { staleIds: [], rebuildableIds: [], staleSteps: [] };
}

export interface DeleteResult {
  deleted: string[];
  /** Clips destroyed alongside the frame they were rendered from. */
  clips: number;
}

/**
 * Destroy a disconnected node, and the pixels behind it.
 *
 * Gated on being disconnected first. That gate is the whole safety model here:
 * this is the one operation in the product that cannot be undone, and requiring
 * a separate, reversible step in front of it means nobody reaches it by
 * mis-clicking a context menu.
 *
 * Clips rendered FROM the frame go with it. A clip is an artefact of one
 * specific frame — it has no meaning once that frame is gone, and leaving it
 * behind would leave a playable video whose source the canvas can no longer
 * show. Frame children are refused instead of cascaded: those are real steps
 * with work in them, and deleting somebody's storyboard because they deleted
 * one frame is not a thing to do quietly.
 *
 * The pixels go before the record, deliberately. A Firestore document with no
 * image is recoverable confusion; an image with no document is unreachable and
 * permanent.
 */
export async function deleteNode(runId: string, uid: string, nodeId: string): Promise<DeleteResult> {
  const db = adminDb();
  const nodesRef = db.collection('runs').doc(runId).collection('nodes');
  const nodes = await loadNodes(runId);

  const node = nodes.find((n) => n.id === nodeId);
  if (!node) throw new Error('no such node');
  if (node.kind === 'avatar' || node.id === 'root') throw new Error('the source avatar cannot be deleted');
  if (!node.removedFromSequence) throw new Error('disconnect it first, then delete');

  const children = nodes.filter((n) => n.parentId === nodeId);
  const frameChildren = children.filter((n) => n.kind === 'frame');
  if (frameChildren.length) {
    throw new Error(
      `${frameChildren.length} step${frameChildren.length > 1 ? 's are' : ' is'} still built on this frame — disconnect ${frameChildren.length > 1 ? 'those' : 'that'} first`,
    );
  }
  const clipChildren = children.filter((n) => n.kind === 'video');
  const doomed = [node, ...clipChildren];

  const { adminStorage } = await import('./firebaseAdmin');
  const { deleteVideo } = await import('./r2');
  const bucket = adminStorage().bucket(
    process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET || 'restage-studio.firebasestorage.app',
  );

  for (const n of doomed) {
    const key = (n as { videoKey?: string }).videoKey;
    if (key) await deleteVideo(key).catch(() => {});
    // Frames are written to a path derived from their own id, so it can be
    // rebuilt here rather than parsed back out of a signed download URL.
    if (n.kind === 'frame') {
      await bucket.file(`users/${uid}/runs/${runId}/nodes/${n.id}.jpg`).delete().catch(() => {});
    }
  }

  const batch = db.batch();
  for (const n of doomed) batch.delete(nodesRef.doc(n.id));
  await batch.commit();

  return { deleted: doomed.map((n) => n.id), clips: clipChildren.length };
}

/**
 * Move a shot earlier or later in the cut.
 *
 * FREE, and that is the whole reason this can exist. While every step was an
 * edit of the one before, moving shot 5 in front of shot 3 meant shot 5 no
 * longer descended from what it had been painted on top of, and both it and
 * everything after would have had to be regenerated. Shots are photographed
 * independently now — each against the run's look — so their order carries no
 * information about how they were made. Rearranging them is exactly as cheap as
 * rearranging clips on a timeline, which is what a person expects a storyboard
 * to be.
 *
 * The chain is rewritten so the canvas and lineageOf() still read left to right
 * in the new order. Each node keeps its OWN children, which is what makes this
 * safe: alternates and rendered clips belong to their shot and travel with it.
 */
export async function reorderShot(
  runId: string,
  nodeId: string,
  direction: 'earlier' | 'later',
): Promise<{ order: string[]; movedTo: number }> {
  const db = adminDb();
  const nodesRef = db.collection('runs').doc(runId).collection('nodes');
  const nodes = await loadNodes(runId);

  const chain = lineageOf(nodes);
  const at = chain.findIndex((n) => n.id === nodeId);
  if (at === -1) throw new Error('that shot is not in the cut');

  const to = direction === 'earlier' ? at - 1 : at + 1;
  if (to < 0 || to >= chain.length) {
    throw new Error(direction === 'earlier' ? 'that is already the first shot' : 'that is already the last shot');
  }

  const order = [...chain];
  [order[at], order[to]] = [order[to], order[at]];

  const batch = db.batch();
  order.forEach((n, i) => {
    batch.update(nodesRef.doc(n.id), {
      parentId: i === 0 ? 'root' : order[i - 1].id,
      stepNo: i + 1,
    });
  });

  /*
   * The plan moves with it.
   *
   * The left panel is what a person reads as the shape of the ad, so leaving it
   * in the old order while the canvas and the render use the new one would mean
   * two answers to "what order is this in" — and the one they read would be the
   * wrong one.
   */
  const runRef = db.collection('runs').doc(runId);
  const plan = ((await runRef.get()).data()?.plan ?? []) as Record<string, unknown>[];
  if (plan.length === chain.length) {
    const moved = [...plan];
    [moved[at], moved[to]] = [moved[to], moved[at]];
    batch.update(runRef, {
      plan: moved.map((p, i) => ({ ...p, stepNo: i + 1 })),
      updatedAt: Date.now(),
    });
  }

  await batch.commit();
  return { order: order.map((n) => n.id), movedTo: to + 1 };
}
