/*
 * Editing the sequence after the agent has built it.
 *
 * The tree is not a gallery of independent images. Each step EDITS the frame
 * before it, so the chain from the avatar to the last frame is a single
 * continuous take — which is what makes the sequence read as a storyboard
 * rather than six unrelated pictures.
 *
 * That is also what makes editing it non-trivial. Swapping frame 3 for an
 * alternate does not just change frame 3: frames 4, 5 and 6 were generated by
 * editing the OLD frame 3, so they now descend from an image that is no longer
 * in the sequence. They are not wrong, exactly — they are answers to a question
 * that was withdrawn.
 *
 * So the operations here do two things: rewire the lineage, and mark what the
 * rewiring invalidated. Nothing is regenerated automatically. Every rebuilt step
 * is a paid generation and twenty seconds of somebody's time, so the decision
 * to spend that belongs to the person, with the count and the cost in front of
 * them.
 *
 * Nothing is deleted either. A replaced frame stays on the canvas as an
 * alternate, because the tree's whole claim is that it shows what happened.
 */
import { adminDb } from './firebaseAdmin';

import {
  descendantsOf,
  summarise,
  type LineageNode,
  type RewireResult,
} from './sequence';

/* Re-exported so existing importers keep working and there is still one
   definition of each. */
export {
  lineageOf,
  descendantsOf,
  isOutOfSequence,
  shotPlan,
  rebuildEstimate,
  type LineageNode,
  type RewireResult,
} from './sequence';

async function loadNodes(runId: string): Promise<LineageNode[]> {
  const snap = await adminDb().collection('runs').doc(runId).collection('nodes').orderBy('createdAt').get();
  return snap.docs.map((d) => ({ id: d.id, ...(d.data() as Omit<LineageNode, 'id'>) }));
}

/**
 * Put `replacementId` where `targetId` sits in the sequence.
 *
 * Both are attempts at the same step with the same parent, so the swap is a
 * re-pointing of children rather than a move: whatever was built on top of the
 * target is now built on top of the replacement. The target stays on the canvas
 * as an alternate.
 */
export async function promoteFrame(runId: string, targetId: string, replacementId: string): Promise<RewireResult> {
  const db = adminDb();
  const nodesRef = db.collection('runs').doc(runId).collection('nodes');
  const nodes = await loadNodes(runId);

  const target = nodes.find((n) => n.id === targetId);
  const replacement = nodes.find((n) => n.id === replacementId);
  if (!target || !replacement) throw new Error('no such frame');
  if (replacement.kind !== 'frame' || target.kind !== 'frame') throw new Error('only frames can be swapped');
  if (!replacement.frameUrl) throw new Error('that frame has no image yet');

  const children = nodes.filter((n) => n.parentId === targetId);

  const batch = db.batch();
  for (const child of children) {
    batch.update(nodesRef.doc(child.id), { parentId: replacementId, stale: true });
  }
  // The replacement takes the target's place in the numbering, so the plan and
  // the canvas agree about which step this is.
  batch.update(nodesRef.doc(replacementId), { stepNo: target.stepNo, stale: false });
  await batch.commit();

  // Everything downstream is stale, not just the direct children: step 5 was
  // edited from step 4, which was edited from the frame that just changed.
  const result = summarise(children.flatMap((c) => [c, ...descendantsOf(nodes, c.id)]));
  if (result.staleIds.length) {
    const b2 = db.batch();
    for (const id of result.staleIds) b2.update(nodesRef.doc(id), { stale: true });
    await b2.commit();
  }
  return result;
}

/**
 * Take a frame out of the sequence.
 *
 * Its children reattach to its parent, so the chain stays unbroken and the
 * steps after it still have something to have been edited from. They are stale
 * for the same reason as a swap: their source changed.
 */
export async function removeFrame(runId: string, nodeId: string): Promise<RewireResult> {
  const db = adminDb();
  const nodesRef = db.collection('runs').doc(runId).collection('nodes');
  const nodes = await loadNodes(runId);

  const node = nodes.find((n) => n.id === nodeId);
  if (!node) throw new Error('no such frame');
  if (node.id === 'root') throw new Error('the source avatar cannot be removed');

  const children = nodes.filter((n) => n.parentId === nodeId);
  const newParent = node.parentId ?? 'root';

  const batch = db.batch();
  for (const child of children) batch.update(nodesRef.doc(child.id), { parentId: newParent, stale: true });
  /* Marked rather than deleted: the canvas is a record of what happened, and a
     frame that silently vanishes makes the record a lie.

     Only the one flag. This also wrote status:'rejected', which made the node
     claim two different things about itself — the tree draws "taken out" for
     the flag and "you rejected this" for the status, both absolutely positioned
     at the same offset, so they rendered on top of each other. Taking a frame
     out is not a verdict on it; it is often removed BECAUSE it was fine
     somewhere else. */
  batch.update(nodesRef.doc(nodeId), { removedFromSequence: true });
  await batch.commit();

  const result = summarise(children.flatMap((c) => [c, ...descendantsOf(nodes, c.id)]));
  if (result.staleIds.length) {
    const b2 = db.batch();
    for (const id of result.staleIds) b2.update(nodesRef.doc(id), { stale: true });
    await b2.commit();
  }
  return result;
}

