'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { CREATIVE_TEMPLATES, type CreativeTemplate } from '@/lib/templates';

/*
 * Templates are shown as motion, not prose.
 *
 * The previous gallery gave each template an emoji, a gradient and two lines of
 * copy, which asked the user to imagine the result. A template is a LOOK, and a
 * look is understood in a second of video and not at all from a paragraph. Each
 * card is a real clip generated by this product's own pipeline: hovering plays
 * it, and the poster frame stands in until then.
 *
 * The clips are muted, loop, and only load on demand (preload="none") — twelve
 * autoplaying videos would cost more bandwidth than the run the user came for.
 */

interface TemplateGalleryProps {
  selectedTemplateId: string | null;
  onSelectTemplate: (template: CreativeTemplate) => void;
}

const CATEGORIES = ['All', 'Sci-Fi', 'Cinematic', 'Social UGC', 'Artistic', 'Retro', 'Gaming'] as const;

export function TemplateGallery({ selectedTemplateId, onSelectTemplate }: TemplateGalleryProps) {
  const [category, setCategory] = useState<string>('All');
  const [expanded, setExpanded] = useState<string | null>(null);

  const filtered = CREATIVE_TEMPLATES.filter((t) => category === 'All' || t.category === category);
  const counts = CREATIVE_TEMPLATES.reduce<Record<string, number>>((acc, t) => {
    acc[t.category] = (acc[t.category] ?? 0) + 1;
    return acc;
  }, {});

  return (
    <div className="w-full">
      <div className="flex items-center gap-1.5 overflow-x-auto pb-2">
        {CATEGORIES.map((cat) => {
          const n = cat === 'All' ? CREATIVE_TEMPLATES.length : (counts[cat] ?? 0);
          if (!n) return null;
          return (
            <button
              key={cat}
              type="button"
              onClick={() => setCategory(cat)}
              className={`shrink-0 rounded-chip px-3 py-1.5 text-[12.5px] font-medium transition-colors ${
                category === cat ? 'bg-primary text-primary-ink' : 'text-ink-3 hover:bg-subtle'
              }`}
            >
              {cat} <span className="tnum opacity-60">{n}</span>
            </button>
          );
        })}
      </div>

      <div className="mt-3.5 grid grid-cols-2 gap-3.5 sm:grid-cols-3 lg:grid-cols-4">
        {filtered.map((tpl) => (
          <TemplateCard
            key={tpl.id}
            tpl={tpl}
            selected={selectedTemplateId === tpl.id}
            expanded={expanded === tpl.id}
            onToggleExpand={() => setExpanded((cur) => (cur === tpl.id ? null : tpl.id))}
            onSelect={() => onSelectTemplate(tpl)}
          />
        ))}
      </div>
    </div>
  );
}

function TemplateCard({
  tpl,
  selected,
  expanded,
  onToggleExpand,
  onSelect,
}: {
  tpl: CreativeTemplate;
  selected: boolean;
  expanded: boolean;
  onToggleExpand: () => void;
  onSelect: () => void;
}) {
  const videoRef = useRef<HTMLVideoElement>(null);
  const [hasClip, setHasClip] = useState(true);
  const [playing, setPlaying] = useState(false);

  const play = useCallback(() => {
    const v = videoRef.current;
    if (!v || !hasClip) return;
    // play() rejects when the browser blocks autoplay or the source is missing;
    // either way the poster stays up and nothing is broken.
    v.play().then(() => setPlaying(true)).catch(() => {});
  }, [hasClip]);

  const stop = useCallback(() => {
    const v = videoRef.current;
    if (!v) return;
    v.pause();
    v.currentTime = 0;
    setPlaying(false);
  }, []);

  // Motion is an accessibility question: someone who asked their OS for less of
  // it should not get an autoplaying clip on every hover.
  const [allowMotion, setAllowMotion] = useState(true);
  useEffect(() => {
    const mq = window.matchMedia('(prefers-reduced-motion: reduce)');
    setAllowMotion(!mq.matches);
    const on = () => setAllowMotion(!mq.matches);
    mq.addEventListener('change', on);
    return () => mq.removeEventListener('change', on);
  }, []);

  return (
    <div
      className={`group relative flex flex-col overflow-hidden rounded-card border bg-panel transition-colors ${
        selected ? 'border-accent ring-2 ring-accent/25' : 'border-line hover:border-line-strong'
      }`}
      onMouseEnter={allowMotion ? play : undefined}
      onMouseLeave={stop}
    >
      <button
        type="button"
        onClick={onSelect}
        aria-label={`Use the ${tpl.name} template`}
        className="relative block aspect-[9/13] w-full overflow-hidden bg-subtle text-left"
      >
        <video
          ref={videoRef}
          src={`/templates/${tpl.id}.mp4`}
          poster={`/templates/${tpl.id}.jpg`}
          muted
          loop
          playsInline
          preload="none"
          onError={() => setHasClip(false)}
          className="h-full w-full object-cover"
        />

        {/* A gradient, so white type stays legible over any frame. */}
        <span className="pointer-events-none absolute inset-x-0 bottom-0 h-2/5 bg-gradient-to-t from-black/80 to-transparent" />

        {!playing && hasClip && allowMotion && (
          <span className="pointer-events-none absolute right-2 top-2 flex items-center gap-1 rounded-chip bg-black/55 px-1.5 py-1 text-[9px] font-bold tracking-[0.06em] text-white backdrop-blur-sm">
            <svg width="8" height="8" viewBox="0 0 24 24" fill="currentColor" aria-hidden><path d="M8 5v14l11-7z" /></svg>
            HOVER
          </span>
        )}

        {tpl.badge && (
          <span className="pointer-events-none absolute left-2 top-2 rounded-chip bg-white/90 px-2 py-0.5 text-[9.5px] font-bold uppercase tracking-[0.06em] text-black">
            {tpl.badge}
          </span>
        )}

        <span className="pointer-events-none absolute inset-x-0 bottom-0 p-2.5">
          <span className="block text-[13.5px] font-bold leading-tight text-white drop-shadow">{tpl.name}</span>
          {/* The keywords ARE the answer to "what is this template using" —
              three concrete nouns beat a sentence of atmosphere. */}
          <span className="mt-1 flex flex-wrap gap-1">
            {tpl.keywords.slice(0, 3).map((k) => (
              <span key={k} className="rounded bg-white/20 px-1.5 py-0.5 text-[9.5px] font-medium text-white backdrop-blur-sm">
                {k}
              </span>
            ))}
          </span>
        </span>

        {selected && (
          <span className="pointer-events-none absolute inset-0 flex items-center justify-center bg-accent/25">
            <span className="flex items-center gap-1.5 rounded-chip bg-accent px-2.5 py-1.5 text-[11px] font-bold text-white">
              <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3.4" strokeLinecap="round" strokeLinejoin="round" aria-hidden><path d="M20 6L9 17l-5-5" /></svg>
              SELECTED
            </span>
          </span>
        )}
      </button>

      <div className="flex items-center justify-between gap-2 border-t border-line px-2.5 py-2">
        <span className="truncate text-[11px] font-semibold text-ink-3">{tpl.category}</span>
        <button
          type="button"
          onClick={onToggleExpand}
          aria-expanded={expanded}
          className="shrink-0 text-[11px] font-semibold text-accent hover:underline"
        >
          {expanded ? 'Less' : `${tpl.presetSteps.length} steps`}
        </button>
      </div>

      {/* Expanded: the actual plan this template will run. The most honest thing
          a template can show is the work it is about to do. */}
      {expanded && (
        <div className="rs-enter border-t border-line bg-subtle px-2.5 py-2.5">
          <ol className="flex flex-col gap-1.5">
            {tpl.presetSteps.map((s, i) => (
              <li key={s.label} className="flex gap-1.5">
                <span className="tnum mt-px shrink-0 text-[10px] font-bold text-ink-4">{i + 1}</span>
                <span className="text-[11px] leading-snug text-ink-2">{s.label}</span>
              </li>
            ))}
          </ol>
          <p className="mt-2 border-t border-line pt-2 text-[10.5px] leading-snug text-ink-4">{tpl.cameraMotion}</p>
        </div>
      )}
    </div>
  );
}
