import { NextResponse } from 'next/server';
import { z } from 'zod';
import { adminDb, requireUid } from '@/lib/firebaseAdmin';
import { consume, tooMany } from '@/lib/rateLimit';
import { deleteNode, disconnectNode, promoteFrame, rebuildEstimate, restoreFrame } from '@/lib/lineage';
import { rebuildStaleSteps } from '@/lib/orchestrator';

/*
 * Editing the sequence: swap a frame, take one out, rebuild what that broke.
 *
 * Swapping and removing are free and instant — they rewire the tree and mark
 * what is now stale. Rebuilding is the expensive one, so it is a separate call:
 * the first two tell the client how many steps would need regenerating and how
 * long that takes, and the person decides whether to spend it.
 */
export const runtime = 'nodejs';
export const maxDuration = 300;

/*
 * Disconnect and delete are deliberately two actions, not one.
 *
 * Detaching something from the canvas and destroying it are different risks.
 * Disconnecting is instant, reversible and free; deleting is the only operation
 * in this product that cannot be undone, and it is reachable ONLY from a
 * disconnected node. That ordering is the safety model — nobody reaches an
 * irreversible action by mis-clicking one item in a context menu.
 *
 * Both apply to clips as well as frames, because "I do not want this any more"
 * is the same sentence about either.
 */
const Body = z.discriminatedUnion('action', [
  z.object({ action: z.literal('swap'), targetId: z.string().min(1), replacementId: z.string().min(1) }),
  z.object({ action: z.literal('disconnect'), nodeId: z.string().min(1) }),
  z.object({ action: z.literal('reconnect'), nodeId: z.string().min(1) }),
  z.object({ action: z.literal('delete'), nodeId: z.string().min(1) }),
  z.object({ action: z.literal('rebuild') }),
]);

export async function POST(req: Request, ctx: { params: Promise<{ runId: string }> }) {
  const { runId } = await ctx.params;

  let uid: string;
  try {
    uid = await requireUid(req);
  } catch {
    return NextResponse.json({ error: 'sign in first' }, { status: 401 });
  }

  const runSnap = await adminDb().collection('runs').doc(runId).get();
  if (!runSnap.exists || runSnap.data()!.uid !== uid) {
    return NextResponse.json({ error: 'no such run' }, { status: 404 });
  }

  const parsed = Body.safeParse(await req.json().catch(() => null));
  if (!parsed.success) return NextResponse.json({ error: 'unknown sequence action' }, { status: 400 });

  try {
    if (parsed.data.action === 'rebuild') {
      // The only branch that generates anything, so the only one that spends.
      const rate = await consume(uid, 'run');
      if (!rate.ok) return tooMany(rate);

      const steps = await rebuildStaleSteps(runId, uid);
      return NextResponse.json({ rebuilding: steps, ...rebuildEstimate(steps) });
    }

    if (parsed.data.action === 'delete') {
      const gone = await deleteNode(runId, uid, parsed.data.nodeId);
      return NextResponse.json({ deleted: gone.deleted.length, clips: gone.clips });
    }

    const result =
      parsed.data.action === 'swap'
        ? await promoteFrame(runId, parsed.data.targetId, parsed.data.replacementId)
        : parsed.data.action === 'reconnect'
          ? await restoreFrame(runId, parsed.data.nodeId)
          : await disconnectNode(runId, parsed.data.nodeId);

    /* Priced on the frames alone. A rendered clip downstream is invalidated too,
       but it is not regenerated by a rebuild, so charging the user three
       minutes for it — and calling it "step 99" — was wrong twice. */
    return NextResponse.json({
      staleSteps: result.staleSteps,
      staleCount: result.rebuildableIds.length,
      ...rebuildEstimate(result.rebuildableIds.length),
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'that did not work';
    return NextResponse.json({ error: msg }, { status: 400 });
  }
}
